[baker.gus] Step2
next-step/spring-roomesacpe-waiting-kakao pull request #1
Opened 2023-01-26 09:15 UTC by jgus52

step2까지 진행하여 PR 드립니다.

auth 패키지를 nextstep에서 분리했습니다.

예약 대기와 관련된 요구사항을 추가했습니다.

filter에 대한 코멘트 주셔서 참고하여 interceptor를 filter를 적용해봤습니다.

리뷰 부탁드려요

2023-01-27 13:17 UTC, sehan requested changes
인증 페키지 리팩토링, 에약대기 구현 잘 해주셨습니다. 👏👏👏
추가로 filter 로 인증, 인가 구현까지 멋집니다. 👍

에약대기 관련해서 중복대기번호생성 이슈가 있어서 관련 코멘트 남겼습니다.
그외 소소한 개선 코멘트 추가했습니다.

중복대기번호생성 이슈는 예약대기등록시 중요한 이슈이기 때문에 개선요청 드립니다.

2023-01-27 13:17 UTC, sehan commented on src/main/java/auth/domain/JwtTokenProvider.java
> -import org.springframework.stereotype.Component;
component scan 의존을 제거 한다는건 spring 의존을 제거하는 의도를 가진것으로 보입니다. 그렇다면 Value 또한 제거 해보면 어떨까요? 
Value 를 제거하면 nextstep 에서 Java Configuration 으로 빈등록 할때 어떻게 처리하면 좋을지 고민해 보면 좋겠습니다. 😊

2023-01-27 13:17 UTC, sehan commented on src/main/java/nextstep/service/ReservationService.java
> +        return reservationWaitingDao.save(new ReservationWaiting(member, schedule, waitNum));
동시에 다수의 사용자가 예약대기를 신청하면 동일한 waitNum 을 받을 가능성이 있습니다. 그렇게 되면 같은 대기번호를 가지는 예약대기자가 발생하게 되는 위험이 있습니다. 
동일한예약대기번호를 발급하지 않도록 개선이 필요합니다.

2023-01-27 13:17 UTC, sehan commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +    }
filter 로 잘구현하셨습니다 👏👏👏

2023-01-27 13:17 UTC, sehan commented on src/main/java/auth/presentation/LoginMemberArgumentResolver.java
> +            throw new AuthenticationException();
TokenFilter 가 인증에 대한 모든 처리를 담당하고 있으면 여기서 인증관련 exception 을 던질 필요는 없을거 같습니다.   LoginMemberArgumentResolver 는 인증이 필요한 controller 메소드에 사용되는것이고  TokenFilter 에 의해 전달된 login 사용자의 id 를 가지고 UserDetails 객체를 바인딩 해주면 되지 않을까요?

2023-01-30 06:05 UTC, jgus52 commented on src/main/java/nextstep/service/ReservationService.java
> +        return reservationWaitingDao.save(new ReservationWaiting(member, schedule, waitNum));
unique constraint와 Transactional을 추가했는데 충분한가요?

2023-01-30 15:11 UTC, sehan approved these changes
동일한 예약대기번호로 대기예약이 생성되는 문제잘 해결하셨습니다. 👏👏👏
성능측면에서 추가적으로 고민해볼 사항을 코멘트로 남겨두었습니다. 
이번 step 은 merge 하도록 하겠습니다.  😊

2023-01-30 15:11 UTC, sehan commented on src/main/java/nextstep/config/AuthConfiguration.java
> +        return new JwtTokenProvider(secretKey, validityInMilliseconds);
👍

2023-01-30 15:11 UTC, sehan commented on src/main/java/nextstep/service/ReservationService.java
> +        return reservationWaitingDao.save(new ReservationWaiting(member, schedule, waitNum));
unique constraint 로 data 의 무결성을 확보하여 동일한 waitNum 이 예약대기로 발생되는 문제는 해결되었습니다.  문제는 해결되었다고 볼 수 있습니다. 

하지만 성능측면에서는 개선할 부분이 아직 남아 있습니다.
max() 사용해서 waitNum 을 발행하는 현재의 방식으로는 동시에 다수의 요청이 들어왔을때  동일한 waitNum 로 insert 가 수행되고 그중 가장빠른 1개의 요청만 성공하는 코드입니다. data 무결성은 보장했지만 많은 사용자들은 예약대기요청에 실패하여 재시도 하는 상황이 발생하게 됩니다.  

하나의 요청이 findMaxWaitNum() 으로 waitNum 을 가져와서 save() 하는 시간동안 다른 요청들이 findMaxWaitNum() 을 호출하면 동일한 waitNum 을 가져오기 때문 입니다. 
 
대기번호발급은 atomic 하게 처리되어야 합니다. 대기번호발급과정에는 다른 개입을 허용하지 않아야 합니다.  이 부분을 해결하면 성능측면까지 개선된 예약대기 시스템이 될 수 있습니다.

2023-01-30 15:11 UTC, merged