[herbi.sf8] 방탈출 예약 대기 관리 Step1,2
next-step/spring-roomesacpe-waiting-kakao pull request #39
Opened 2023-01-31 07:49 UTC by herbi1411

안녕하세요! 이번주 과제인 방탈출 예약 대기 관리 1,2단계 리뷰 요청 드립니다.
이번 미션은 다음과 같이 2가지 기능을 구현하는 것이었습니다!
```
1. auth 패키지를 nextstep 패키지에서 분리
2. 예약 대기 관리 기능 만들기
```
패키지 분리 관련해서는 interface를 auth 패키지에 만들고 nextstep 패키지에서 구현체를 만드는 방법으로 패키지 분리를 시도해봤습니다.
예약 대기 관리는 ReservationWaiting이라는 패키지를 만들어서 관련 기능을 구현한 클래스를 만들었습니다. 만들다보니 기존의 Reservation과 겹치는 코드가 많았습니다.😢

기존의 Interceptor에서 dao를 통해 멤버를 조회했었는데 지난 리뷰에서 말씀해주신대로 Service를 사용하도록 구성했습니다! (패키지 분리때문에 실제로 UserAuthenticatorImpl에서 사용합니다.) 추가로 기존에는 AdminInterceptor만 있었는데 LoginInterceptor를 생성해서 LoginInterCeptor에서 DB조회를 통해 멤버를 검증하고, AdminInterceptor에서는 멤버의 역할만 검증하도록 했습니다. LoginInterceptor가 먼저 실행되며, request의 attribute에 role속성을 삽입해서 AdminInterceptor에서 사용하도록 했습니다. 

Filter 사용에 대해서도 고민해봤는데 현재 Interceptor에서 멤버를 검증하는 과정에서 MemberService를 사용하고 있기 때문에 Interceptor가 나은 것 같아서 그대로 활용했습니다! 현재는 SpringBoot에 웹서버가 내장되며 Filter에서도 Spring Context를 사용할 수 있지만, Filter는 Spring Context 외부인 Web Context에 있도록 설계된 것이라고 봐서 이와 같은 결정을 했습니다!

이번 미션 요구사항에 대한 구현 방법은 README에 간략하게 작성했습니다!

2023-02-01 12:42 UTC, maythree requested changes
고생 많으셨습니다.😁
auth 관련해서 몇가지 코멘트 드렸고, 예약 대기의 구현 방식에 대해서는 조금 더 고민해보시면 좋으실 것 같아서 따로 코멘트들 남기지 않았습니다. 조금 더 고민해보시고 다시 말씀해주시면 해당 부분은 다시 코드리뷰 드리도록 하겠습니다.

2023-02-01 12:42 UTC, maythree commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        request.setAttribute("role", role);
해당 값이 변경될 경우, 다른 클래스에 영향이 없을까요?

2023-02-01 12:42 UTC, maythree commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        String role = userAuthenticator.getRole(Long.parseLong(id))
Role Enumeration이 존재하는데 String으로 처리하신 이유가 있으실까요?

2023-02-01 12:42 UTC, maythree commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        request.setAttribute("role", role);
혹시 인증과 인가의 차이에 대해서 알고계실까요?? 그리고 만일 사용자 정보가 추가되어 다른 조건으로 분류를 해야한다면 확장이 자유로울까요??

2023-02-01 12:42 UTC, maythree commented on src/main/java/auth/jwt/TokenExtractor.java
> +        String token;
별도의 변수를 선언해서 처리하신 이유가 있으실까요?? 아래와 같이 변경 가능할것 같네요.
지금의 경우 선언된 변수 하위에 로직이 없어서 한번에 보이지만, 코드가 길어지거나 이와 같은 변수들이 많아질 경우 코드 가독성이 떨어질 수 있으니 사유가 있지 않다면 지양하시는게 좋으실 것 같습니다.
```java
try {
    return Optional.ofNullable(tokenWithClass.split(" ")[1]);
} catch (NullPointerException | IndexOutOfBoundsException e) {
    return Optional.empty();
}
```

2023-02-01 12:42 UTC, maythree commented on src/main/java/nextstep/config/AuthConfig.java
> +
불필요하게 생성되는 빈도 존재하는 것 같네요. 확인해보시면 좋으실 것 같습니다.

2023-02-01 12:42 UTC, maythree commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +        registry.addInterceptor(new LoginInterceptor(jwtTokenProvider, userAuthenticator, tokenExtractor))
Interceptor들만 AuthConfig에서 빈으로 안만들고 직접 생성해서 사용하신 이유가 따로 있으실까요?

2023-02-01 12:42 UTC, maythree commented on src/main/java/nextstep/member/UserAuthenticatorImpl.java
> +            return Optional.empty();
memberService.findById(id)에서 Null에 대한 검증이 끝났는데, 다시 Optional로 감싸신 이유가 있으실까요?

2023-02-01 12:42 UTC, maythree commented on src/main/java/nextstep/reservationwaiting/ReservationWaiting.java
> +public class ReservationWaiting {
새로운 예약 조건이 추가되면 또 이와 같은 방식으로 모델이 계속 추가 되는게 최선일까요?? 예약 조건이 추가될 가능성이 적다고 볼 수 있을까요??

2023-02-02 09:19 UTC, herbi1411 reviewed
코멘트 해주신 부분 수정 진행해봤습니다! Reservation - ReservationWaiting간 중복 문제는 일단 테이블을 나누는 것이 맞다는 판단은 했는데 중복을 줄이는 방법이 떠오르지 않아 제대로 수정을 진행하지 못했습니다. 😢 해당부분은 더 고민해보겠습니다.

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/nextstep/reservationwaiting/ReservationWaiting.java
> +public class ReservationWaiting {
말씀해주신 것처럼 예약관련 기능이 생기면 모델을 하나씩 파면 개발자에게 매우 고통일 것 같습니다.. 이번 과제에서도 Waiting을 새로 만들면서 겹치는 코드가 많아서 이게 맞나 싶었습니다.

그래서 해결책으로 생각한 것 중 하나가 DB에서 테이블을 reservation으로 합치고 하나의 모델만 사용할 까 생각했습니다. 예약이 된 상태면 waitNum을 0으로 하고, 1 이후부터는 대기 상태로 처리하는 방법입니다. 하지만 그렇게 되면 예약에만 필요한 속성(ex. 예약금 납부여부) 혹은 예약 대기에만 필요한 속성이 있다면 데이터 하나에 필요 없는 정보가 많아질 수 도 있고, 스키마 수정도 자주 일어날 것 같아서 좋은 방법이 아니라고 생각했습니다.

그렇다면 waiting 모델을 따로 구성하는 것이 더 좋은 방법 같은데 findById 등 로직이 거의 완벽히 일치하는 코드들의 중복을 막을 수는 없을 까 생각해봤습니다. 그래서 ReservationFundamental 모델을 하나 둬서 Reservation과 Reservation이 이 모델을 상속하게 하면 중복 코드를 줄일 수 있지 않을 까 생각해봤습니다. dao, Service 모델도 ReservationFundamental에 대해  만들고 Reservation과 ReservationWaiting이 이를 상속하게 해서 findById 등은 따로 구현하지 않게 만들어보려고 했습니다. 하지만 이렇게 하다보니 로직 파악이 더 어려워지고, 오류가 나도 찾기가 힘들어지는 것 같아서 중간에 다시 원래 구조로 되돌리게 됐습니다.

그래서 결국 다시 예약관련 기능이 생기면 모델을 하나씩 파야하는 구조로 돌아오게 됐습니다.😭 각 모델 안에서 중복되는 코드라도 줄여보고자 Dao 계층에서 select, inner join의 반복되는 sql 구문을 상수 처리 해서 사용하게 했습니다.

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/nextstep/member/UserAuthenticatorImpl.java
> +            return Optional.empty();
memberService에서 null이 뜨면 MemberNotFound(404) 에러가 나도록 설정했습니다. 하지만 인증 단계에서 사용할 때는 인증관련에러(401)가 나게 해야하므로 try-catch를 활용해 servie에서 익셉션을 검출해서 401에러가 나도록 했습니다. 이때 UserAuthenticatorImpl에서 바로 throw 할수 있지만, auth 패키지에서 예외를 던지는 것이 더 자연스러운 것 같아서 UserAuthenticatorImpl에서는 맴버를 찾지 못하면 Optional empty를 반환하도록 하고 이후 LoginService에서 예외를 던졌습니다.

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/nextstep/config/WebMvcConfiguration.java
> +        registry.addInterceptor(new LoginInterceptor(jwtTokenProvider, userAuthenticator, tokenExtractor))
인터셉터 등록하는 과정에서 빈 등록을 놓쳤네요. 그러면서 WebMvcConfiguration 파일에 loginService 등 인터셉터 생성에 필요한 빈들이 추가되며 지저분해진 것 같습니다. AuthConfig에서 Bean 등록 하도록 수정했습니다!

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/nextstep/config/AuthConfig.java
> +
userAuthenticatorImpl이 nextstep 패키지에 있기 떄문에 configuration이 아니라 component 어노테이션으로 등록할 수 있다는 말씀이실까요..? 일단 그렇게 수정했습니다. 다른 클래스에 대해서는 일단 모두 2곳 이상에서 사용되는 것 같아 싱글톤으로 관리되면 메모리가 절약될 것 같아서 빈으로 등록했는데 jwtTokenProvider나 tokenExtractor와 같은 util느낌(?)의 클래스들은 빈으로 등록하지 않고 사용하는 것이 더 나은 방법일까요??

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/auth/jwt/TokenExtractor.java
> +        String token;
try, catch 만들 때 습관적으로 변수를 선언하고 try문으로 들어갔어서 불필요한 변수 선언이 발생했습니다. 말씀해주신대로 수정했습니다!! 그리고 Optional에 null이 들어갈 수 있도록 하는 것이 적절하지 않은 것 같아 `ofNullable`을 `of`로 변경했습니다!

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        request.setAttribute("role", role);
인증은  유저가 누구인 지 신원을 확인하는 것이고, 인가는 유저에 대해 권한이 있는지 검사하는 것입니다. 제 프로젝트 구조에선 LoginInterceptor에서 토큰을 통해 유저인지 인증하고, AdminInterceptor에서 토큰을 통해 멤버를 조회해 어드민인지 확인해 권한을 인가하는 것 같습니다. 

 사용자 정보가 추가 돼서 다른 조건으로 분류해야 한다면 현재는 LoginInterceptor, AdminInterceptor를 모두 변경해야 해서 확장이 어려운 구조인 것 같습니다. 어떻게 변경해야할 지 생각해봤는데 사용자 분류를 LoginService의 메서드로 구현하고, Interceptor에서 그 메서드를 호출하는 방식으로 변경하면 더 나아질 것 같아서 이와같이 구조를 수정해봤습니다!

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        String role = userAuthenticator.getRole(Long.parseLong(id))
auth 패키지에서 nextstep 패키지에 대한 의존성을 가지지 않게 하기위해 nextstep 패키지에 있는 Role enum을 사용하지 않으려고 String으로 했었습니다. 그런데 지금 보니까 AdminInterceptor에서 Role enum을 사용하고 있었네요..🥲 마지막에 의존성 확인을 안했더니 실수로 의존관계가 다시 생긴 것 같습니다. 이번에 수정하면서 admin에 대한 검증을 LoginService의 메서드 호출로 처리하는 구조로 변경하려고 해서 Interceptor에서 Role 관련 내용은 모두 제거하겠습니다!

2023-02-02 09:19 UTC, herbi1411 commented on src/main/java/auth/interceptor/LoginInterceptor.java
> +        request.setAttribute("role", role);
`request.setAttribute("role", role);` 이부분에 대해 말씀해주신 것 맞으실까요?? 제가 이렇게 처리한 이유는 LoginInterceptor에서 DB 조회를 통해 member가 유효한지 검사하고 role을 request header에 설정해서 AdminInterceptor에서는 다시 DB 조회할 필요 없이 role을 검증하기 위함이었습니다. 그런데 말씀해주신 것처럼 이렇게하면 interceptor끼리 의존성도 생기고 유지보수가 어려워질 것 같습니다. 그리고 지금 생각해보니까 LoginInterceptor에서는 굳이 member DB 조회를 할 필요가 없을 것 같아서 토큰만 검증하도록 바꿨고(이미 JWT의 유효성 검사 통과로 인증이 처리된 것이기 때문에), AdminInterceptor에서 LoginService → UserAuthenticatorImpl 호출을 통해 member DB를 조회하도록 변경했습니다!

2023-02-03 07:43 UTC, maythree approved these changes
코멘트 드린 부분 수정하시고 고민하시니라 고생 많으셨습니다👍
원활한 다음 과제 진행을 위하여 우선은 해당 과제는 머지 처리하도록 하겠습니다.
아직 해결하시지 못한 모델 설계에 대한 고민은 학습을 위하여 추후에도 고민을 좀 더 해보셔도 좋으실 것 같습니다. 상태나 조건이 추가되어 변경이 발생되는 이런 경우는 실무에서도 빈번하기 때문에 이러한 부분을 수정하기 위해 사용되는 비용은 가치가 크다고 생각합니다. 실무에서는 이런 부분을 간과하고 넘어가게 된다면 더 큰 유지보수 비용이 발생될 수 있습니다.

2023-02-03 07:43 UTC, merged