[marcus.min] 방탈출 예약 1단계 & 2단계
next-step/spring-roomesacpe-waiting-kakao pull request #41
Opened 2023-01-31 08:21 UTC by ekzm8523

[과제 링크](https://edu.nextstep.camp/s/GiKTqpMP/ls/MlRKpeWQ)
안녕하세요 웨이드~ 오늘만 두 번째 PR이네요!!
부담이 되실까 걱정이 되긴 하지만 오늘까지가 데드라인이라 어쩔 수 없이 올리게 되었네요 😭

## 고민했던 부분

### 1. 예약과 예약대기를 어떻게 분리 할 것인가
동료들의 구현 방법들을 취합 한 결과 다음과 같은 방법들이 존재하는 것 같아요.
1. Reservation & Reservation Waiting 테이블을 각각 만든다.
2. Reservation에 rating이라는 컬럼을 추가한다.
3. Reservation에 create_datetime이라는 컬럼을 사용해 가장 빠른 예약은 Reservation, 그 뒤의 예약들은 순서를 매겨서 Reservation Waiting으로 구별

저는 위의 방법들 중 3번째 방법을 선택했습니다.
이유는 예약 생성, 변경, 삭제가 빈번할 것 같아서 매번 모든 예약들을 가져와서 수정해주면 너무 오버헤드가 클 것 같았습니다.
하지만 이 방법은 조회의 비용이 비쌉니다. 매번 create_datetime을 조회하며 순서를 계산합니다.

- 1 Q ) 결국 Trade-off 관계인데 웨이드라면 어떤식으로 예약과 예약대기를 분리할 것 같으신가요?

### 2. JdbcTest를 진행할 때 초기 데이터를 어디서 셋팅해야 하는가?
현재 Dao 테스트가 스크립트에 저장된 데이터를 기반으로 테스팅되기 때문에 테스트코드만으로 결과를 예측하기 힘듭니다.
이는 제 3자가 보는 입장에서 스크립트를 이해하고 테스팅코드를 봐야하기 때문에 클린하지 못하다고 생각합니다.
그렇다고 이를 코드에 전부 명시해주기엔 테스트코드가 너무 무거워질 것 같습니다.

### 3. JdbcTest Auto Increament 문제
JdbcTest에서 data.sql를 통해 초기 데이터를 셋팅해줄 때 ID를 명시해주면 Auto Increment에서 인지하지 못하고 데이터를 추가할 때 Duplicated primary key error를 뱉게 됩니다.
그래서 어쩔 수 없이 스크립트에서 ID를 명시하지 않고 DB에게 key 생성을 위임하면서 각 테스트의 독립성을 유지하기 위해 매번 테이블을 삭제하고 새로 생성해주도록 하였습니다.

- 2 & 3 Q ) 웨이드는 어떤식으로 테스트 데이터 셋팅을 해주나요?

이번 코드리뷰도 잘 부탁드립니다 🙇🙇

2023-02-01 07:45 UTC, wade-lim requested changes
고생하셨습니다!!
잘 구현해주셔서 리뷰 드릴게 많지 않네요 😅

---

> 1. 예약과 예약대기를 어떻게 분리 할 것인가

선택하신 방법이 조금 조회 비용이 높더라도 간단하게 구현 가능한 좋은 방법인 것 같네요.

2번의 경우 rating 이 어떤 의미인지는 모르겠지만, 우선순위 개념이라면 사실상 create_datetime 과 크게 다를게 없어보이고, 순서의 개념(1번=에약, 2번~=예약대기)이라면 말씀하신대로 삽입/삭제 비용이 너무 클 것 같네요.

1번의 경우 테이블을 좀 더 명확하게 구분할 수 있다는 장점이 있을 것 같은데, 추후 예약 대기 전용 필드가 추가되는 경우가 생길 것 같으면 테이블을 분리하는 것도 좋을 것 같습니다.
(ex: 대기자 알림 여부 필드 추가 등등)

> 2. JdbcTest를 진행할 때 초기 데이터를 어디서 셋팅해야 하는가?

테스트 데이터를 공통으로 생성해두고 사용할지, 테스트 별로 만들어두어야 할지에 대한 문제인 것 같네요.

일반적인 동작만 확인해도 되는 간단한 테스트는 공용 데이터를 사용하고, 코너 케이스 테스트와 같이 특수한 데이터가 필요한 경우 해당 테스트를 위한 별도의 데이터를 만들어서 사용하는 것이 좋을 것 같습니다.

> 3. JdbcTest Auto Increament 문제

DB 의 auto_increment 값을 직접 설정할 수 있는 쿼리가 있을텐데, id 를 직접 지정하여 삽입한 경우 요 값도 같이 조정해줘야 실 DB 와 비슷한 환경이 만들어질 것 같네요.
(실 DB 에서는 데이터가 삽입되는 동안 auto_increment 값이 자동으로 늘어날테니까요~)

```sql
ALTER TABLE {table} AUTO_INCREMENT={number}
```

그리고 데이터 수정이 필요한 테스트라면 테스트 후 테이블을 재생성하는게 맞는 것 같네요~

2023-02-01 07:45 UTC, wade-lim commented on src/main/java/auth/AuthenticationException.java
> +public class AuthenticationException extends RestAPIException {
[의견]
Exception 에 `@ResponseStatus(code = HttpStatus.BAD_REQUEST)` 어노테이션을 사용할 수 있더라구요~

2023-02-01 07:45 UTC, wade-lim commented on src/main/java/nextstep/WebMvcConfiguration.java
>      }
[확인]
의존 관계가 있는 Bean 은 내부에서 필요한 Bean 을 컨테이너에서 주입 받도록 하는게 좋을거 같아요~

```java
// 스프링 컨테이너가 클래스와 같은 기본 정보로부터 Bean 을 특정하지 못하는 상황에서는 @Qualifier("beanName") 과 같이 bean 이름을 직접 지정할 수도 있습니다.
// 등록된 JwtTokenProvider Bean 이 1개라서 여기서는 직접 지정하지 않아도 됩니다.
public LoginService(@Qualifier("jwtTokenProvider") JwtTokenProvider jwtProvider) {
  return new LoginService(authenticationProvider, jwtProvider);
}
```

추가) 과제 제약 사항이었네요 😓

2023-02-01 07:45 UTC, wade-lim commented on src/main/java/nextstep/WebMvcConfiguration.java
>  }
[의견]
jwtTokenProvider, loginService 는 직접 생성하는 것보다 스프링 컨테이너에서 생성된 객체를 주입 받아서 사용하는게 좋을 것 같아요~

Bean 으로 등록되어 있는데 함수 호출로 직접 생성하는 경우 객체가 싱글턴으로 관리되지 않아서요.

2023-02-01 07:45 UTC, wade-lim commented on src/main/java/nextstep/reservation/ReservationDao.java
> +        return jdbcTemplate.query(sql, reservationRowMapper, themeId, Date.valueOf(date));
[의견]

Java 15 부터는 multiline string 사용 가능할거에요~

```java
String x = """
  ...
"""
```

2023-02-01 09:55 UTC, ekzm8523 reviewed
auto increment를 alter로 수정할 수 있군요!!! 감사합니다 ㅎㅎ

2023-02-01 09:55 UTC, ekzm8523 commented on src/main/java/nextstep/WebMvcConfiguration.java
>      }
아 Qualifier라는 것도 있군요!!
이런 달콤한 팁 너무 좋습니다 👍👍

2023-02-01 09:55 UTC, ekzm8523 commented on src/main/java/nextstep/WebMvcConfiguration.java
>  }
`Configuration` 어노테이션이 Bean으로 등록된 메서드는 다시 호출하더라도 ApplicationContext에 생성해놓은 Bean이 존재하는지 확인하기 때문에 싱글턴으로 관리가 되는 것 같아요!!

2023-02-02 05:16 UTC, wade-lim approved these changes
고생하셨습니다!!

2023-02-02 05:16 UTC, merged